import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useFruit } from '../providers/list/fruit-provider'

const Home: NextPage = () => {
  const { fruit, setFruit } = useFruit()
  
  const onClick = () => {
    const _fruit = {
      fruit: {
        name: '',
        ids: ['abc'],
        fruit: {
          'abc': {
            age: 27,
            name: 'ohoshi'
          }
        }
      }
    }
    setFruit(_fruit)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        current fruit
        <div className={styles.code}>
          {JSON.stringify(fruit)}
        </div>
        <button onClick={onClick}>click</button>
      </main>
    </div>
  )
}

export default Home
