import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          Operation immer useReducer
          <code className={styles.code}>pages/index.js</code>
        </p>
        <p>
          Use immer with <code className={styles.code}>useReducer</code>
        </p>
        <a href="https://github.com/immerjs/use-immer" className={styles.anchor}>https://github.com/immerjs/use-immer</a>
      </main>
    </div>
  )
}

export default Home
